### ISSUE TITLE
createServer not working

### ISSUE THREAD

**Issue by Linux123123** [EiskalterFreund/nodeactyl-v1-support#3]
**Describe the bug**
`createServer` isn't working

**To Reproduce**
1. Have API already connected (works on other things then `createServer`)
2. call `createServer`
3. Console log the output
4. See `undefined`

**Expected behavior**
It should create a server

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser: Firefox
 - Version: 82.0.2 

**Additional context**
Using this: (all the values replaced with real ones of course)
``` javascript
application.createServer("latest", "NameOfServer", "OwnerID", "PackID", "EggID", "DockerImage", "StartupCMD", "RAM", "Swap", "DiskSpace", "IO", "CpuCores", "MaxDatabases", "AmtOfAllocations").then(res => {
    console.log(res) // returns a server object (see below)
}).catch(error =>{
    console.log(error);
})
```

**Comment by numbereddev** [comment]
I will fix it as soon as possible

**Comment by numbereddev** [comment]
I have an question on wich host are you using this function
Edit: Because falixnodes blocked creating server by api

**Comment by Linux123123** [comment]
I have the panel self hosted so this isn't a problem.

**Comment by numbereddev** [comment]
Ok
Edit: May i have to host panel my self to test

**Comment by Linux123123** [comment]
You can have my api key. Ether way I am testing. How can I send it?

**Comment by numbereddev** [comment]
Maybe per discord?

**Comment by Linux123123** [comment]
> Maybe per discord?

Yes, mine is Linux123123#8664

**Comment by Linux123123** [comment]
I have created my own API library, so I don't need this anymore.

**Comment by EiskalterFreund** [comment]
oh ok

**Comment by EiskalterFreund** [comment]
Cannot fix it sorry

**Comment by numbereddev** [comment]
Hey @Linux123123  I now implemented Admin API You can test it out!
