### ISSUE TITLE
getRAMUsage() function is returning n/a instead of datas

### ISSUE THREAD

**Issue by IceroDev** [EiskalterFreund/nodeactyl-v1-support#4]
**Describe the bug**
getRAMUsage() function returns n/a and not ram usage

**To Reproduce**
1. Test a getRAMUsage() function
2. Look at the result of the command

**Expected behavior**
Showing current ram usage

**Screenshots**
https://i.ibb.co/3dvF35C/Capture-d-cran-du-2020-11-02-15-05-20.png
(getCPUUsage and getDiskUsage() are working)

**Additional context**
type : Discord Bot

**Comment by IceroDev** [comment]
nvm, api just return n/a when the server is down.

**Comment by numbereddev** [comment]
ok
