### ISSUE TITLE
Bug with Create Server

### ISSUE THREAD

**Issue by TheGoodIn** [EiskalterFreund/nodeactyl-v1-support#5]
Looks like they added backups to the API, can you please update the wrapper it will not let me create a server

**Comment by EiskalterFreund** [comment]
What is exactly the problem?

**Comment by numbereddev** [comment]
Oh Ic, I thought I fixed it, but wait I will look into it

**Comment by numbereddev** [comment]
Also it is fixed did you migrate to the new code of the new verision, cuz at the end of all parameters is also an backups parameter type there like 0 or 1 or idk.

**Comment by numbereddev** [comment]
@TheGoodIn

**Comment by TheGoodIn** [comment]
So you want another perm that says "0"

**Comment by numbereddev** [comment]
Also at the end of the params for the create server method you need also a param called backups with as an integer / string

**Comment by TheGoodIn** [comment]
So I just add another number and comma?

**Comment by numbereddev** [comment]
yes but only at the end

**Comment by TheGoodIn** [comment]
[
  {
    code: 'ValidationException',
    status: '422',
    detail: 'The File Name variable field is required.',
    meta: { source_field: 'environment.STARTUP_FILE', rule: 'required' }
  },
  {
    code: 'ValidationException',
    status: '422',
    detail: 'The Automatic Package Update/Installation variable field is required.',
    meta: {
      source_field: 'environment.AUTO_UPDATE_PACKAGE',
      rule: 'required'
    }
  }

**Comment by numbereddev** [comment]
hmm

**Comment by numbereddev** [comment]
ok ik error, will fix tmr

**Comment by numbereddev** [comment]
I fixed it @TheGoodIn  It should not happen anymore, thanks for the report ;D

**Comment by numbereddev** [comment]
If problems shall occur open an issue, I will close this issue, bye
